steps:
  # 1. Zbuduj obraz Dockera
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/springboot-app", "."]
  # 2. Wdróż obraz na Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "springboot-app"
      - "--image=gcr.io/$PROJECT_ID/springboot-app"
      - "--platform=managed"
      - "--region=us-central1" # Wybierz region, w którym działa Twoja usługa
      - "--allow-unauthenticated" # Ustawienia publicznego dostępu (opcjonalne)

images:
  - "gcr.io/$PROJECT_ID/springboot-app"
